src/index.js
Compares the directory containing .git and the directory of containing husky to find the directory of the package.json file.  The relative path derived from this comparison is then added to the scripts in the .git/hooks files.  
This allows npm run --json to execute properly, instead of resulting in the following error:
```
npm ERR! npm run-script [<pkg>] <command>
npm ERR! not ok code 0
```
=> handle projects that do not have package.json in root

src/index.js
There is definitely a better way to do this, passing any args along to the script to consider or ignore as necessary, but this should let users actually act on the commit message when using this hook.
=> pass $1 to script if hook is commitmsg

README.md
I find using `npm uninstall` clearer to any of its aliases (`remove`, `rm`, `r`, `un`, `unlink`) mainly because of its counterpart being `npm install`.
Hopefully you'll agree.
Thanks!
=> Replace `npm rm` with `npm uninstall`

README.md
I’ve spent some time to understand that names of Git hooks and npm scripts are not the same.
=> Clarify available npm script names

bin/install.js, bin/uninstall.js, package.json
There is no guaranty that `node` binary is present in the user's path during module installation. It's a common practise to use `/usr/bin/env node`, so call `/opt/nodejs/5/bin/node /opt/nodejs/5/bin/npm install` could work.
Unfortunately, I don't have any Windows experience and no possibility to test that. So it'd be awesome if anybody could verify everything still works on Windows.
=> Fix bin scripts to use proper nodejs binary

src/index.js
The following commit broke our setup: https://github.com/typicode/husky/commit/4d43602938097dd727fbcd4a3196bd0ebb6e9c11
This is a simple fix to prevent errors when `$*` expands to more than one value.
Cheers!
=> Fix parameter handling

src/index.js
=> fix: add support for windows gui clients

README.md
We had to rename the project. This is the new name and link.
=> HyperTerm is now called Hyper

src/index.js
`nvm` couldn't be loaded when a specific version of `npm` was in the path even when a `.nvmrc` was added to the project root. This change allows to place a file `.nvmrc` into the project root which will be picked up by husky.
Additionally two apparent bugs are fixed:
* `exists` doesn't seem to be a command neither on macOS nor on Linux, might be a typo
* the test for the file `nvm.sh` is wrong
=> Fix loading `nvm`

.npmignore
Removes files in test/ and the .travis.yml from the npm registry to make the package a bit smaller.
=> Add .npmignore (closes #121)

src/index.js, test/index.js
Worktree's `.git` file contains absolute path to repository.
`path.join` incorrectly concatenates `/path/to/worktree`
with `/path/to/real/.git/worktrees/worktree` to
`/path/to/worktree/path/to/real/.git/worktrees/worktree`
instead of simple `/path/to/real/...`
Using `path.resolve` instead of `path.join` resolves this problem
while relative paths of submodules still works correctly.
=> Correct work with worktrees

__tests__/index.js, src/utils/get-hook-script.js
Spaces in file path for windows are not escaped.
So in the hook file we have something like this:
`cd Solution/05. Web/Service.Web
`
Should be: 
`cd Solution/05.\ Web/Service.Web
`
=> Fix. Escape spaces in window file path

src/utils/get-hook-script.js
When using Husky inside WSL, there was a problem with spaces in Windows paths:
```
.git/hooks/pre-commit: 31: export: (x86)/NVIDIA: bad variable name
```
This commit fixes it by adding double quotes for PATH export.
=> Fixed PATH export

src/install.js
If not, the info will be `skippingpost-commit hook (existing user hook)`,
It will be nice like that `skipping post-commit hook (existing user hook)`
=> add the space between 'skipping' word and hookName

HOOKS.md, src/hooks.json
Hello @typicode , and thank you for the great library.
I found [`sendemail-validate`](https://git-scm.com/docs/githooks#_sendemail_validate) hook is missing, and then added.
The hook seems to be added recently.
ref: https://www.spinics.net/lists/git/msg303675.html
I appreciate you if you would check this PR when you have time.
=> Add sendemail-validate githook

src/utils/get-hook-script.js
This fixes a bug where `nvm use` runs twice on Mac environments:
```bash
$ git commit -am "Test"
Found '/Users/vitorbal/Code/test/.nvmrc' with version <6.2.2>
Now using node v6.2.2 (npm v3.9.5)
Found '/Users/vitorbal/Code/test/.nvmrc' with version <6.2.2>
Now using node v6.2.2 (npm v3.9.5)
husky > npm run -s precommit (node v6.2.2)
```
I assume this is related to the two calls to `load_nvm`:
```bash
load_nvm /Users/vitorbal/.nvm
load_nvm /usr/local/opt/nvm
```
The second call only happens if you're in a Mac environment:
```js
if (process.platform === 'darwin') {
arr.push(
stripIndent(
`
load_nvm /usr/local/opt/nvm`
)
)
}
```
---
After the fix:
```bash
$ git commit -am "Test"
Found '/Users/vitorbal/Code/zapier/.nvmrc' with version <6.2.2>
Now using node v6.2.2 (npm v3.9.5)
husky > npm run …
```
=> Fix `nvm use` running twice on mac

README.md, package-lock.json, package.json, src/runner/index.ts, typings/cosmiconfig/index.d.ts
Overview
-----
This PR makes it so that users can specify their hooks in a few more ways besides a top-level key in their `package.json`. This is accomplished by using [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) which would add support for:
* A `.huskyrc`, `.huskyrc.json`, or `.huskyrc.y[a]ml` file
* A `husky.config.js` file that exports a config object
Motivation
-----
My team is already using husky and we want to move to the `beta` version due to its speed improvements but we're not too keen on adding a new top-level key in our `package.json`. We'd much prefer a `.huskyrc` file which would lead to a clearer separation of concerns and follow an existing pattern that is already in use by many packages.
=> Support more methods for defining config/hooks

src/installer/__tests__/index.ts
Hello,
I was wondering why beta is trying to install on CI server (CircleCI) and failing due to hooks folder does not exist in the CI container. Problem is with the compilation from TS.
``` js
function install(gitDir, huskyDir) {
console.log('husky > setting up git hooks');
var userDir = pkgDir.sync(path.join(huskyDir, '..'));
var conf = getConf(userDir);
console.log(is_ci_1); // true
console.log(is_ci_1.default); // undefined
if (is_ci_1.default && conf.skipCI) {
console.log('CI detected, skipping Git hooks installation"');
return;
}
```
=> test: isCI should be defined

docs.md, src/installer/__tests__/__snapshots__/getScript.ts.snap, templates/hook.sh
From git's [pre-push hook documentation](https://git-scm.com/docs/githooks#_pre_push
):
> Information about what is to be pushed is provided on the hook’s standard input with lines of the form: `<local ref> SP <local sha1> SP <remote ref> SP <remote sha1> LF`
With this PR, stdin is stored in GIT_STDIN env variable so user hooks can access it.
Should fix: https://github.com/typicode/husky/issues/93
=> add GIT_STDIN env variable

README.md
According to https://libraries.io/npm/husky/dependent-repositories, `husky` is used by more than 18k repositories
=> Update dependent repositories number at readme

package.json
uses _/usr/bin/env bash_ instead of system level _/bin/bash_
=> upgrade: run-node to 1.0.0

README.md
This corrects a couple issues I saw.
- The AppVeyor URL was broken.
- A reader of `README.md` might not be reading it on GitHub, so use an absolute URL to `docs.md`.
=> fix broken AppVeyor URL; use absolute URL for docs.md

src/runner/index.ts
Currently date-fns has this `package.json` and husky fails because the version is invalid.
```js
{
"version": "DON'T CHANGE; IT'S SET AUTOMATICALLY DURING DEPLOYMENT; ALSO, USE YARN FOR DEVELOPMENT"
}
```
I think that husky shouldn't be cared about package linting. Husky is used by user for any kind of linting and shouldn't force user to anything.
=> Prevent package normalizing

src/runner/index.ts
=> advise '--no-verify' does not skip post-* hooks

src/upgrader/index.ts
By default npm includes a trailing newline when it writes the `package.json`. this preserves that behavior to not cause churn in the file in the most common case.
https://github.com/npm/cli/blob/4c65cd952bc8627811735bea76b9b110cc4fc80e/lib/install/update-package-json.js#L48
=> upgrader: Add trailing newline to package.json

src/upgrader/__tests__/index.ts, src/upgrader/index.ts
Thanks for providing a nice tool `husky-upgrade`!
I'm using the tool [`commitlint`](https://github.com/marionebl/commitlint), and my `package.json` is below:
```json
{
"scripts": {
"commitmsg": "commitlint -E GIT_PARAMS"
}
}
```
I'm so happy that `husky-upgrade` will update `GIT_PARAMS` to `HUSKY_GIT_PARAMS`, like this:
```json
{
"husky": {
"hooks": {
"commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
}
}
}
```
=> `husky-upgrade` replace GIT_PARAMS with HUSKY_GIT_PARAMS

src/installer/__tests__/__snapshots__/getScript.ts.snap, src/installer/__tests__/getScript.ts, src/installer/getScript.ts
To make debugging easier, add more info about husky and which package installed it:
```
```
Thanks to @garybernhardt for the idea :+1:
=> Add generated by informations in hook script

src/installer/__tests__/__snapshots__/getScript.ts.snap, src/installer/getScript.ts
This PR enables `stdin` if hook is running in terminal.
Since there are many PRs regarding this feature, some on old code, I'm creating this new one. In order for everyone who contributed to get credits, I'll add [`Co-authored-by`](https://help.github.com/articles/creating-a-commit-with-multiple-authors/) fields to the commit.
I've never tried this approach before. but from my understanding it should appear in your contribution graph as if your PRs were merged 🤞
In any case, credits and thanks go to @jesstelford, @joelgallant, @tanhauhau and @ikokostya for this feature.
Note: to be able to add you, GitHub seems to need an email as mentioned [here](https://help.github.com/articles/creating-a-commit-with-multiple-authors/), please send it to me using my mail or DM me on Twitter. I'll leave …
=> Enable stdin if terminal

src/installer/resolveGitDir.ts
@typicode Hey feel free to reformat and pull it in.
Thx
=> Fix: git-worktree

.travis.yml, DOCS.md, package-lock.json, scripts/ci-husky-skip-hooks.js, src/runner/index.ts
Requested in #487.
This adds support for a  `HUSK_SKIP_HOOKS` environment variable. When this is set to `1` or `true`, husky skips running the hooks.
=> Add HUSKY_SKIP_HOOKS env var to skip running hooks

package.json, src/installer/__tests__/__snapshots__/getScript.ts.snap, src/installer/getScript.ts
This fix has multiple purposes that improve the compatibility with Yarn at little cost:
- First, it ensures that the Husky command will run with the same pipeline as the one used by Husky's users when they run their scripts. It previously wasn't the case, because Husky was using `run-node` to "detect" the version of Node to use whereas Yarn users were using `yarn run [...]` (which enforces the Node version to be the same one as the one used to run Yarn itself).
- Second, starting from Yarn 2 we're looking to keep packages inside their tarballs as much as possible. In the context of `run-node` this causes problems, because `run-node` is a shellscript and can only be executed when unpacked. Using `yarn husky-run` avoids the issue altogether.
- Third, when working with PnP environments, if …
=> Adds an optional settings to use Yarn to run Husky

src/installer/__tests__/index.ts, src/installer/index.ts
[Disable auto-install](https://github.com/typicode/husky/blob/8920e331f78ccbfe4f41de753a268cdcba3da2e4/DOCS.md#disable-auto-install) in the documentation suggests to set `HUSKY_SKIP_INSTALL` to `1` to skip automatic installation of Git hooks. However, Husky actually only skipped installation if `HUSKY_SKIP_INSTALL` was set to `true` (instead of `1`).
I’ve changed the condition to test for both `1` and `true` (similar to how it’s already done in [`debug.ts`](https://github.com/typicode/husky/blob/8920e331f78ccbfe4f41de753a268cdcba3da2e4/src/debug.ts#L2)) and added a test.
=> Fix HUSKY_SKIP_INSTALL=1 not skipping install

DOCS.md, src/installer/gitRevParse.ts
=> Correct typos

run.js
Having just upgraded from 2.4.1, I've found that the hooks fail with Yarn support enabled:
```
$ HUSKY_DEBUG=1 git commit
husky:debug pre-commit hook started
husky:debug calling husky through Yarn
yarn run v1.17.0
$ […]/node_modules/.bin/husky-run pre-commit ''
[…]/node_modules/.bin/husky-run: 1: […]/node_modules/.bin/husky-run: /bin: Permission denied
[…]/node_modules/.bin/husky-run: 2: […]/node_modules/.bin/husky-run: Syntax error: "(" unexpected
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Looks like Yarn is trying to exec husky-run directly, while the npm codepath just runs it as a Node script. Adding a shebang fixes the issue.
=> Add shebang to run.js

src/installer/__tests__/__snapshots__/getScript.ts.snap, src/installer/getScript.ts
There's a problem in the 4.0.0-0 where the parameters sent to Yarn are as such:
```
yarn "" husky-run pre-commit
```
This empty second argument is caused by explicitly passing `$1 $2` as parameter (Yarn doesn't need a second argument, so Bash is replacing it with an empty string).
This diff fixes that by using `"$@"` instead, which expands to the list of arguments passed to the function (so `"npx" "--no-install"` for npx, and simply `"yarn"` for Yarn).
=> Fixes "yarn run"

package.json
Fixes: https://github.com/typicode/husky/issues/565
From that issue:
> On windows, there's no `true`. Looking at other popular packages, I believe `|| exit 0` is a more reliable way to handle this ([1](https://github.com/remy/nodemon/blob/master/package.json), [2](https://github.com/styled-components/styled-components/blob/master/packages/styled-components/package.json))
This change was tested by removing the `opencollective-postinstall` script from the .bin folder, and then running `npm run postinstall` in cmd and powershell. In both shells I validated that without this change, the process exits with a non-zero exit code (cannot find 'opencollective-postinstall', cannot find 'true'), and with this change that it exits with an exit code of zero.
=> [Fix] Prevent postinstall from failing on windows

src/installer/__tests__/gitRevParse.ts, src/installer/bin.ts, src/installer/gitRevParse.ts
Use `--git-common-dir` rather than `--absolute-git-dir`
See #580
=> Use --git-common-dir

package-lock.json, package.json, src/global.d.ts, src/installer/bin.ts
Instead of having is-ci call ci-info's ci.isCI, we might as well call ci.isCI within the installation directly. This allows us to shorten the dependency branch by 1 step which is a trivial amount of gain, but it nonetheless reduces the length of the package-lock
=> Remove is-ci in favor of ci-info

src/installer/bin.ts
When using Yarn v2 there is no console output from installs unless they fail, since husky doesn't change the exit code it seems like the install succeeded when it actually failed
=> fix: use process.exit if install fails

src/installer/bin.ts
Reverts typicode/husky#633 rollbacking for the moment due to #636
=> Revert "fix: use process.exit if install fails"

src/installer/__tests__/__snapshots__/getScript.ts.snap, src/installer/getScript.ts
see https://github.com/yarnpkg/yarn/issues/2998#issuecomment-351424672
fixes #627 
fixes #635
=> fix yarn when running inside winpty

src/installer/getScript.ts
Errors pop up in prepush event when GIT_STDIN contains newlines and invalid variables
=> Bugfix: prevent errors

package-lock.json, package.json, src/installer/__tests__/checkGitVersion.ts, src/installer/bin.ts, src/installer/checkGitVersion.ts
Log an error if Git is `<2.13.0`
=> Check Git version

sh/husky.sh, src/installer/__tests__/__snapshots__/scripts.ts.snap
in [readme](https://github.com/typicode/husky/blob/master/README.md#upgrading-from-014) it says:
> Starting with 1.0.0, husky can be configured using .huskyrc, .huskyrc.json, .huskyrc.js or husky.config.js file.
=> fix: husky.config.js not .huskyrc.config.js

bin/run.js, husky.js
It's useful when some git GUI apps can't run `node -v` directly
=> Show runtime node version when exit

sh/husky.sh, src/installer/__tests__/__snapshots__/scripts.ts.snap
close #682
close #676
close cnpm/cnpm#318
```
npm i cnpm -g
git clone git@github.com:afc163/husky-test.git
cd husky-test
cnpm i
touch README && git add README
git commit -am 'commit message'
```
husky `pre-commit` is not running.
`$packageManager` of husky defined didn't contain `cnpm`, which is using https://github.com/cnpm/npminstall, the `$packageManager` value should be `npminstall`.
It can be fallback to `npx` when `$packageManager` is `npminstall`.
Additionally, fixed `Unknown package manager` logic according to #682 in which @MondoGao had described.
=> fix: cnpm fails due to $packgeManager not matched

scripts/test-install.sh, src/runner/__tests__/index.ts, src/runner/index.ts
=> fix wrong error message

README.md
As per the title, updating the documentation to list all the supported formats for configuration.
https://github.com/typicode/husky/issues/695
=> Adding more supported formats to the README documentation

package-lock.json, package.json, sh/husky.sh, src/installer/__tests__/__snapshots__/scripts.ts.snap
re #727, added .cjs config file support
=> Add .cjs config file support

README.md
Repo create-react-app has been moved from 'facebookincubator' to 'facebook'
=> Changed create-react-app repo url

docs/README.md
Update the v5 documentation to be in line with [pinst](https://github.com/typicode/pinst) by replacing the ([deprecated](https://docs.npmjs.com/cli/v6/using-npm/scripts)) `"prepublish"` hook with `"prepublishOnly"`.
=> Rename "prepublish" to "prepublishOnly" in docs

sh/husky.sh, src/installer/__tests__/__snapshots__/scripts.ts.snap, src/runner/__tests__/index.ts, src/runner/index.ts
=> fix prepare-commit-msg on windows

docs/README.md
I've tried add `commitlint` command to `.husky/pre-commit`, but it's not working.
`.husky/commit-msg` works.
=> docs: `pre-commit` -> `commit-msg` for commitlint

package-lock.json, package.json
This PR fixes a security issues stemming from `semver-regex` which is pulled in via `find-versions`
`find-versions` 4.0.0 depends on `^3.1.2` of `semver-regex`. Previous
versions of `semver-regex` contained a [vulnernability][0]. This was
unlikely to affect `husky` because of how `find-versions` is used, but
the only breaking change in `find-versions` is increasing the minimum
Node.js verison to 10, which is the same as Husky's minimum.
[0]: https://app.snyk.io/vuln/SNYK-JS-SEMVERREGEX-1047770
=> Upgrade find-versions to 4.0.0

docs/README.md
Adds documentation for the configuring of git-flow hooks
=> Add git-flow docss

docs/README.md
`npm exec` is only available on NPM 7+. Using `npx` is cross-compatible with npm 6 and 7.
=> docs: use npx vs. npm exec

docs/README.md, package-lock.json, package.json, src/commands/init.ts, test/init.sh, test/sub-dir.sh
Many thanks to @nathansmith #884 for suggesting this improvement.
=> docs: prepare script instead of postinstall

docs/README.md
CLI was throwing a warning when using `yarn install husky --save-dev`, so this PR updates the command in the docs to `yarn add husky --dev`
=> docs: update yarn install to yarn add

packages/husky/src/husky.sh
Since the `exitCode` is defined on line 22, It is possible to directly exit on line 28 and keep the `exitCode`, Line 24 only checks if `exitCode` is not 0 and echoes the error.
=> refactor(husky): remove redundant exit on husky.sh

packages/husky-init/src/index.ts
The code removed is also the first line of `appendScript` which is called immediately afterwards. No need to do it *N* times. Once is enough.
=> removed duplicated code

docs/README.md
The "Locally installed binaries" section was missing a `# or` comment between the `npx` and `yarn` example. I brought the comment directly from the "HUSKY_GIT_PARAMS" section.
=> docs: align the examples

src/index.ts
This resolves [this issue](https://github.com/typicode/husky/issues/1000) by covering for the case that `git rev-parse` returns null, which may be the case in a CI Docker image that does not bundle the git cli
=> fix: cover case where git rev-parse returns null

docs/README.md
I think it's easier to read and the condition is now correct with the negation.
=> fix: readme confusing condition to disable install in CI

.github/workflows/node.js.yml
- Update `actions/setup-node` to `v2`
- Enable built-in cache for npm packages that comes with `actions/setup-node@v2.2.0` (optional)
Closes #1007.
[Release notes for `actions/setup-node v2.2.0`](https://github.com/actions/setup-node/releases/tag/v2.2.0)
=> ci: update actions/setup-node to v2, enable cache

husky.sh
I do not know why this works but this version of `husky.sh` now works well both in terminal and in WebStorm
=> Fix pre-commit hook in WebStorm under macOS

docs/README.md
Hello, this PR fixes a tiny typo in `docs/README.md`.
I think the `--only` parameter of `npm ci` should be `--only=production` same as Line 254.
=> docs: fix typo on `docs/README.md`

docs/index.html
Thought it would look nice to add a dog emoji as a favicon for the docs site.
[It has ok browser support](https://caniuse.com/link-icon-svg), but I can generate and add standard `.ico` and `pngs` for wider support if it's something that you would like.
=> feat: add dog emoji as favicon

.husky/commit-msg, .husky/pre-commit, docs/README.md, husky.sh, src/index.ts
According with the best practices of shell scripting, the right way to invoke the _shebang_ is `#!/usr/bin/env shell`
Reference: https://www.cyberciti.biz/tips/finding-bash-perl-python-portably-using-env.html
=> Use /usr/bin/env sh instead of direct path of sh

husky.sh
Previously, the `husky.sh` script would export the empty 'readonly' variable, along with 'husky_skip_init' which has a value of 1.
Now, the script sets 'husky_skip_init' to 1, and properly gives is the 'readonly' and 'exported' attributes.
=> Actually set 'husky_skip_init' as readonly in `./husky.sh`

.husky/commit-msg, .husky/pre-commit, docs/README.md, husky.sh, src/index.ts, test/1_default.sh, test/2_in-sub-dir.sh, test/3_from-sub-dir.sh, test/4_not-git-dir.sh, test/5_set-add.sh, test/6_git_command_not_found.sh, test/functions.sh
`basename`/`dirname` will treat `$0` as an option if it starts with a `-`; e.g. for `-husky`:
```sh
dirname: invalid option -- 'h'
Try 'dirname --help' for more information.
```
Why did my directory start with a hyphen instead of a dot in the first place? I'd... rather not answer this, but it's related to my setup and not a bug in this project.
=> Force `basename`/`dirname` to treat `$0` as an argument

src/index.ts
All links on git.io will stop redirecting after April 29, 2022.
- https://github.blog/changelog/2022-04-25-git-io-deprecation/
=> chore: remove git.io

src/bin.ts
Hiya,
Spent some time today debugging an issue that I eventually traced back to husky, would have been nice to have the error message identified as such.
Admit this is probably more a yarn issue as all yarn gave me to go on was:
```
➤ YN0000: │ root@workspace:. STDERR fatal: not a git repository (or any of the parent directories): .git
```
But would appreciate this workaround being added, as it also bring it in line with [your other logging](https://github.com/typicode/husky/blob/main/src/index.ts#L6).
Cheers!
=> add `husky -` prefix to logged global error messages

docs/README.md
> The --no-install option is deprecated, and will be converted to --no
https://docs.npmjs.com/cli/v7/commands/npx#compatibility-with-older-npx-versions.
=> docs: replace deprecated npx option

docs/README.md
=> Add pnpm installation

.husky/commit-msg
npx `--no-install` option is deprecated (see [npm docs](https://docs.npmjs.com/cli/v8/commands/npx#compatibility-with-older-npx-versions)).
Use `--no --` instead
=> npx option --no-install replaced with --no -- due to deprecation

docs/README.md
This PR changes `npx --no` command to `npx --no --` in README
Close #1157
=> docs: add double-hyphen flag between npx and the command to run

src/index.ts
Added a console log letting the user know that git must be installed on their machine if it is not found during the `husky install`. Addressed issue #1191.
=> fix: added git not installed error message

docs/README.md
VS Code can get into a weird state where husky `pre-commit`s will fail with `command not found` but the solution is to simply restart VS Code. see https://stackoverflow.com/a/73635509/5504797
=> update docs to add message about restarting vs code

docs/README.md
I scoured a lot of GitHub issues and Stack Overflow problems. The difficulty in just using:
```sh
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
```
is that - by default - nvm.sh will run the default Node version which isn't necessarily the project's node version. This still won't save anybody manually bouncing between Node versions within different projects, but `.nvmrc` is a very common practice and this should assuage people who run Husky in a project using an `.nvmrc` file that differs from their NVM default.
=> Adjust instructions for nvm workaround

.github/workflows/node.js.yml, .github/workflows/npm_publish.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

src/index.ts
Fixes #1177
Solves the issue of a commit hook not being executable on Linux systems when the commit hook was created on a Windows system.
Previously, when a new commit hook was created on a Windows system, the executable bit (which is required by Git on Linux systems to run a commit hook) was not added to the newly created commit hook file because Windows does not keep track of the executable bit of a file. This resulted in commit hooks not working as intended when the repository was cloned onto a Linux system.
To fix this issue, the executable bit will now be added to the file when creating a new commit hook on a Windows system by using the Git command `git update-index --chmod=+x .\path\to\file`. This solution is a bit of a hack since it requires the user to manually commit the file to …
=> Make commit hooks created on Windows executable on Linux

.github/ISSUE_TEMPLATE/issue.md, src/index.ts
Fixed broken links in issue template and ``src/index.js``
This PR changes
- https://typicode.github.io/husky/#/?id=troubleshoot
- https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7
- https://typicode.github.io/husky/#/?id=custom-directory
to
- https://typicode.github.io/husky/troubleshooting.html
- https://typicode.github.io/husky/migrating-from-v4.html
- https://typicode.github.io/husky/guide.html#custom-directory
=> fix: docs link

husky.sh
Sometimes, it is difficult to avoid subshells in POSIX sh (making runtime slower), but in this case, [POSIX specifies](https://pubs.opengroup.org/onlinepubs/009604499/utilities/xcu_chap02.html) a syntax for parameter expansion that gives us a performance improvement.
This uses the **Remove Largest Prefix Pattern** which has a syntax of  `${parameter##word}`. It modifies the variable _parameter_ by greedily removing a pattern from the start of the string.
In the case of this patch, it simply removes everything up to (and including) the last `/` character. Examples:
- Before: `./pre-commit`
- After: `pre-commit`
- Before: `/usr/bin/zsh`
- After: `zsh`
=> perf: Use POSIX-defined parameter expansion

husky.sh
Under most systems, `$XDG_CONFIG_HOME` is not defined. Therefore, in the most common case, Husky would check for the following files in the order:
- `/husky/init.sh`
- `$HOME/.config/husky/init.sh`
- `$HOME/.huskyrc.sh`
Of course, this isn't compliant with the XDG Directory Specification. This fixes the case whwere `XDG_CONFIG_HOME` is not defined - it defaults it to `$HOME/.config`, as per the specification.
=> fix: Do not search for rc file at `/husky/init.sh`

docs/guide.md
`--ignore-scripts` disable dependencies script as well. This argument prevent some dependencies to download binary during installation.
=> docs: prefer delete script prepare compare to ignore scripts

docs/guide.md
See npm's documentation at https://docs.npmjs.com/cli/v8/commands/npm-install#omit
> If the resulting omit list includes `'dev'`, then the `NODE_ENV` environment
> variable will be set to `'production'` for all lifecycle scripts.
=> docs: use NODE_ENV to conditionally install husky

docs/migrating-from-v4.md
The migration guide shows mismatched hooks for the before and after examples, which can be confusing.
=> docs: update hook references in migration guide

docs/.vitepress/config.ts, docs/zh/getting-started.md, docs/zh/guide.md, docs/zh/index.md, docs/zh/migrating-from-v4.md, docs/zh/troubleshooting.md, package-lock.json, package.json
* Add simplified Chinese documentation
* Update vitepress to version 1.0.0-bete.6
=> Add simplified Chinese documentation

bin.js
Fixed an error that occurs on installation if the `scripts` field is not present in package.json.
```
$ npx husky init                                                                                                                                                 ~/ghq/github.com/Rhelixa-inc/epiclock-test-report-generator
Need to install the following packages:
husky@9.0.1
Ok to proceed? (y) 
file:///Users/takuya.fukuju/.npm/_npx/0d92fdd791cc1044/node_modules/husky/bin.js:10
d.scripts.prepare = 'husky'
^
TypeError: Cannot set properties of undefined (setting 'prepare')
at file:///Users/takuya.fukuju/.npm/_npx/0d92fdd791cc1044/node_modules/husky/bin.js:10:21
at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
at async ModuleLoader.import (node:internal/modules/esm/loader:329:24) …
```
=> fix: add scripts field if not present

bin.js
While it may be controversial, text files are generally preferred to end with a newline.
=> fix: insert final newline

bin.js, docs/get-started.md
`npm_package_json`  env is not supported by pnpm now. (but npm and yarn works)
This is not a perfect fix, the user may not run husky init in project root. in this  case, we need more code that npm and yarn user doest't need, I think this is unfair.  So, we can simple add one line here utill the pnpm support it.
The other way is update doc, let users define a env named `npm_package_json` before `husky init`, but I think that is too complex for users.
=> fix: fix init not work on pnpm #1334

docs/how-to.md
=> docs: update install script to mjs and fix CI checks

husky.sh
=> Fix  unbound variable

docs/how-to.md
See #1362
Uses `CI=true` as pointed out by @jerome-benoit
=> docs: fix example

bin.js
See https://github.com/typicode/husky/commit/ec13855c167bcead06523ae43ca1b5152d77810f#r138138417
=> Fix tab detection on install command

docs/.vitepress/config.mts, docs/CNAME, docs/package-lock.json, docs/package.json, docs/zh/get-started.md, docs/zh/how-to.md, docs/zh/index.md, docs/zh/migrate-from-v4.md, docs/zh/troubleshoot.md
* Add Simplified Chinese documentation
* Update vitepress to version 1.0.1
=> docs: add Simplified Chinese documentation

husky, index.mjs
On Windows, under certain circumstances, the path separator is "\".
This change will ensure compatibility with both Linux and Windows path separators
=> Get the path from dirname instead of using Bash variable operators

docs/.vitepress/config.mts, docs/es/get-started.md, docs/es/how-to.md, docs/es/index.md, docs/es/migrate-from-v4.md, docs/es/troubleshoot.md
=> docs: support Spanish documentation

bin.js
Fix to `bin.js` which incorrectly creates a partial example `pre-commit` file when `npx husky init` is called on systems with npm_config_user_agent set.
=> Fix issue where example pre-commit file is generated incorrectly

bin.js
Add husky label to deprecated commands.
Old:
```
install command is DEPRECATED
```
New:
```
husky - install command is DEPRECATED
```
Fixes: https://github.com/typicode/husky/issues/1537
=> fix: add husky label to deprecated warning
