bin/install.js
bin/uninstall.js
package.json

Revert "Fix bin scripts to use proper nodejs binary"

---

README.md
src/index.js

Pass sh parameters from hooks into npm scripts

---

HOOKS.md
src/hooks.json

I really need this for a project I am building asap, if you could just release a new npm version with that feature that would be awesome.
Thanks!

Add missing hooks (Fix issue #52)

---

src/index.js

The current failure message kind of threw me off when I first saw it.

update failure message

---

src/index.js

* Added more accurate error message for `prepare-commit-msg` hook

Update to handle failed prepare-commit-msg

---

README.md

It seems more than 8,000 now!
https://libraries.io/npm/husky/dependent-repositories

Increase project number

---

bin/install.js

Hi,
This closes #172.
Let me know if I need to change something.
Thanks!

added HUSKY_SKIP_INSTALL env variable to skip hook install

---

README.md

The little lock-with-warning-sign was bothering me on npm.

Replace download badge from HTTP to HTTPS.

---

src/upgrader/index.ts

Don't create husky config in package.json if hooks doesn't exist already

perf(husky-upgrade): don't create husky config if no hooks exist

---

CHANGELOG.md
src/installer/__tests__/index.ts
src/installer/index.ts

Create .git/hooks if doesn't exist

---

src/installer/__tests__/__snapshots__/getScript.ts.snap
src/installer/getScript.ts

Thanks to @akazakou for providing the fix

Use . instead of source

---

src/installer/__tests__/index.ts
src/installer/getScript.ts
src/installer/index.ts

Thanks to @arcanis for finding this!
https://github.com/yarnpkg/berry/issues/102

require run-node/run-node instead of .bin/run-node

---

src/installer/__tests__/__snapshots__/getScript.ts.snap
src/installer/getScript.ts
src/runner/index.ts

Running it early in the shell script should make things a little faster.

Move HUSKY_SKIP_HOOKS check to shell script

---

src/installer/__tests__/__snapshots__/getScript.ts.snap
src/installer/getScript.ts

This PR adds support for repository-local huskyrc files.
I moved the execution order because of a separate PR I'm working on.

Adds support for repository-local huskyrc files

---

package.json
scripts/install.sh
src/installer/getScript.ts
src/runner/__tests__/index.ts
src/runner/index.ts

Since https://github.com/typicode/husky/pull/219 has now too many conflicts, I'm recreating it here. All credit goes to @gucong3000 for the original code and idea :+1: 
The PR replaces execa with git bash.

use spawnSync and SHELL env for runner

---

src/runner/__tests__/index.ts
src/runner/index.ts

This way runner script won't rely on husky being in `node_modules`

rely on cwd rather than runner script path

---

package-lock.json
package.json
src/installer/gitRevParse.ts

See https://github.com/typicode/husky/pull/219
Thanks again to @gucong3000

remove execa dependency

---

src/installer/index.ts
src/upgrader/index.ts

https://git-scm.com/docs/githooks#_pre_merge_commit

Add pre-merge-commit support

---

src/installer/__tests__/__snapshots__/getScript.ts.snap
src/installer/getScript.ts

Pretty straightforward PR, minor typo.

Fix typo in getScript

---

appveyor.yml
src/installer/__tests__/__snapshots__/getScript.ts.snap

seems like sh on appveyor is using WSL's sh meaning you might as well be testing on Linux 😆

fix snapshot

---

sh/husky.sh
src/installer/__tests__/__snapshots__/scripts.ts.snap

support spaces in path to husky.local.sh

---

src/installer/__tests__/index.ts
src/installer/localScript.ts
src/installer/mainScript.ts

Don't throw error during uninstall if file doesn't exist

---

README.md

https://github.com/typicode/husky/blob/4e1d440be7e3058036d24e7c5558c09448772af2/sh/husky.sh#L38

Fix "huskyrc.yml" -> ".huskyrc.yml"

---

docs/README.md

docs: add uninstall instructions (closes #849)

---

.github/workflows/node.js.yml

chore: improve ci speed by splitting lint and test

---

docs/index.md

Implementing #1298 (verified/proof: #1249).

docs: clarify client-side hooks are supported

---

husky.sh
package-lock.json

fix: exit code

---

docs/index.md

docs: typo

---

index.js

fix: fix git hooks path on windows

---

docs/.vitepress/config.mts

https://github.com/typicode/husky/pull/1325

docs: add favicon

---

docs/how-to.md

Fix #1381 by adding documentation to `how-to.md`

Fix #1381 Update how-to.md

---

docs/get-started.md

Sorry about the line 80 diff — I edited using the Github GUI. Feel free to close and recreate on your end.

Small typo fix

---

index.js

support pre-merge-commit hook
fixes: #1494

fixes #1494, support pre-merge-commit hook

---

docs/es/index.md

Links to sponsorkit were updated.

dosc: repair support Spanish sponsors links

---

docs/.vitepress/config.mts
docs/es/get-started.md
docs/es/how-to.md
docs/es/index.md
docs/es/troubleshoot.md

I have made some improvements to the Spanish translation and corrected some spelling mistakes.

docs(spanish): improve spanish translation

---

docs/es/index.md

update Spanish documentation to last English documentation commit `3efdbb13c4b46e4b244eb7aede8729d4272b71fd`

docs(spanish): update index.md - 3efdbb1
